# Generated by Django 2.0 on 2018-12-27 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('prodID', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('prodName', models.CharField(max_length=256, verbose_name='Product Name')),
                ('prodCode', models.CharField(max_length=150, verbose_name='Product Code')),
                ('compName', models.CharField(max_length=256, verbose_name='Company Name')),
                ('rate', models.FloatField(verbose_name='Rate')),
                ('per', models.CharField(max_length=15, verbose_name='Per')),
                ('prodPhoto', models.ImageField(blank=True, upload_to='prodImage')),
                ('compID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
    ]
