# Generated by Django 2.0 on 2018-12-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='per',
            field=models.CharField(choices=[('Kg', 'Kg'), ('Pcs', 'Pcs'), ('Bags', 'Bags'), ('Box', 'Box')], max_length=15, verbose_name='Per'),
        ),
    ]
