# Generated by Django 2.0 on 2018-12-27 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181227_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='compID',
            field=models.CharField(max_length=256, verbose_name='Company ID'),
        ),
        migrations.AlterField(
            model_name='products',
            name='compName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='Company Name'),
        ),
    ]
