# Generated by Django 2.0 on 2018-12-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20181227_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='compID',
        ),
    ]
