# Generated by Django 2.0 on 2018-12-28 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_auto_20181228_1100'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billNumber', models.CharField(max_length=256, unique=True, verbose_name='Bill no')),
                ('billDate', models.DateTimeField(auto_now=True, verbose_name='Bill Date')),
                ('createdBy', models.CharField(max_length=150, verbose_name='Created by ')),
                ('billAmount', models.FloatField(verbose_name='Bill Amount')),
                ('billStatus', models.CharField(choices=[('Generated', 'Generated'), ('Bill Paid', 'Bill_Paid')], max_length=50, verbose_name='Bill Status')),
                ('compName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='Company Name')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders', verbose_name='Order ID')),
            ],
        ),
    ]
