# Generated by Django 2.0 on 2019-01-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='billNumber',
            field=models.CharField(max_length=256, verbose_name='Bill no'),
        ),
        migrations.AlterField(
            model_name='bills',
            name='billStatus',
            field=models.CharField(choices=[('Generated', 'Generated'), ('Bill Paid', 'Bill_Paid')], default='Generated', max_length=50, verbose_name='Bill Status'),
        ),
        migrations.AlterField(
            model_name='bills',
            name='createdBy',
            field=models.CharField(default='Accountant', max_length=150, verbose_name='Created by'),
        ),
    ]
