# Generated by Django 2.0 on 2018-12-28 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderDate',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderMonth',
            field=models.DateField(default=datetime.date(2018, 12, 28), verbose_name='Month'),
        ),
    ]
