# Generated by Django 2.0 on 2019-01-12 07:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='itemQuantity',
            field=models.PositiveIntegerField(default=1, max_length=256, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='compName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Company', verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='itemName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Products', verbose_name='Items'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderDate',
            field=models.DateField(default=datetime.date(2019, 1, 12), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderId',
            field=models.CharField(blank=True, max_length=256, unique=True, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderMonth',
            field=models.DateField(default=datetime.date(2019, 1, 12), verbose_name='Month'),
        ),
    ]
