# Generated by Django 2.0 on 2018-12-28 14:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181228_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 28, 14, 24, 45, 341788, tzinfo=utc), verbose_name='Date'),
        ),
    ]
