# Generated by Django 2.0 on 2019-01-16 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190112_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='itemQuantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderDate',
            field=models.DateField(default=datetime.date(2019, 1, 16), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderMonth',
            field=models.DateField(default=datetime.date(2019, 1, 16), verbose_name='Month'),
        ),
    ]
