# Generated by Django 2.0 on 2019-01-17 16:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190116_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='compName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='itemName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Products', verbose_name='Items'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderDate',
            field=models.DateField(default=datetime.date(2019, 1, 17), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderMonth',
            field=models.DateField(default=datetime.date(2019, 1, 17), verbose_name='Month'),
        ),
    ]
