# Generated by Django 2.0 on 2018-12-29 06:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20181229_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 29, 6, 14, 49, 20207, tzinfo=utc), verbose_name='Date'),
        ),
    ]
