# Generated by Django 2.0 on 2018-12-29 06:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20181229_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 29, 6, 17, 4, 222774, tzinfo=utc), verbose_name='Date'),
        ),
    ]
