# Generated by Django 2.0 on 2018-12-29 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20181229_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 29, 6, 48, 47, 116926, tzinfo=utc), verbose_name='Date'),
        ),
    ]
