# Generated by Django 2.0 on 2018-12-29 12:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20181229_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 29, 12, 1, 26, 785958, tzinfo=utc), verbose_name='Date'),
        ),
    ]
