# Generated by Django 2.0 on 2018-12-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('compID', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('compName', models.CharField(max_length=256, verbose_name='Company Name')),
                ('CompAddress', models.TextField(verbose_name='Address')),
                ('compContact', models.CharField(max_length=20, verbose_name='Contact')),
                ('compEmail', models.EmailField(blank=True, max_length=254, verbose_name='Email Id')),
                ('compLocation', models.CharField(blank=True, max_length=150, verbose_name='Location')),
            ],
        ),
    ]
